name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
       
    - name: Choco help
      uses: crazy-max/ghaction-chocolatey@v1.5.0
      with:
        args: -h
     
    - name: Install gperf
      run: |
        Choco install gperf
      shell: bash
      
    - name: Build tdlib for windows
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg.exe install openssl:x64-windows zlib:x64-windows
        cd ..
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build . --config Release
      shell: bash
      
    - name: Upload release asset
      uses: actions/upload-artifact@v2.2.4
      with:	
        name: 'Release'	
        path: './build/Release/'
